/** Kanso Industrial: a calm, touch-friendly local conversion route. */
import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import { SafeAreaView } from "react-native-safe-area-context";
import { convert, formats, type Format } from "../lib/converter";

const sample = '{\n  "project": "Henkanki",\n  "localFirst": true\n}\n';
export default function Home() {
  const [input, setInput] = useState(sample); const [output, setOutput] = useState(""); const [from, setFrom] = useState<Format>("json"); const [to, setTo] = useState<Format>("yaml");
  async function pick() { const file = await DocumentPicker.getDocumentAsync({ type: ["application/json", "application/x-yaml", "text/plain"], copyToCacheDirectory: true }); if (file.canceled) return; const asset = file.assets[0]; setInput(await FileSystem.readAsStringAsync(asset.uri)); setFrom(asset.name.endsWith(".yaml") || asset.name.endsWith(".yml") ? "yaml" : asset.name.endsWith(".json") ? "json" : "text"); setOutput(""); }
  async function share() { if (!output) return; const uri = `${FileSystem.cacheDirectory}henkanki.${to === "text" ? "txt" : to}`; await FileSystem.writeAsStringAsync(uri, output); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "text/plain" }); else Alert.alert("Saved locally", uri); }
  function run() { try { setOutput(convert(input, from, to)); } catch (error) { Alert.alert("Conversion stopped", error instanceof Error ? error.message : "Invalid input"); } }
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.header}><Text style={styles.kicker}>変  LOCAL CONVERSION DESK</Text><Text style={styles.title}>Henkanki</Text><Text style={styles.subtitle}>This file stays on this device.</Text></View><View style={styles.route}><Text style={styles.routeText}>01 INPUT</Text><Text style={styles.arrow}>→</Text><Text style={styles.routeText}>02 PLAN</Text><Text style={styles.arrow}>→</Text><Text style={styles.routeText}>03 OUTPUT</Text></View><View style={styles.card}><Text style={styles.label}>SOURCE FORMAT</Text><View style={styles.row}>{formats.map((format) => <Pressable key={format} onPress={() => setFrom(format)} style={[styles.chip, from === format && styles.chipActive]}><Text style={[styles.chipText, from === format && styles.chipTextActive]}>{format.toUpperCase()}</Text></Pressable>)}</View><Text style={[styles.label, { marginTop: 18 }]}>TARGET FORMAT</Text><View style={styles.row}>{formats.map((format) => <Pressable key={format} onPress={() => setTo(format)} style={[styles.chip, to === format && styles.chipActive]}><Text style={[styles.chipText, to === format && styles.chipTextActive]}>{format.toUpperCase()}</Text></Pressable>)}</View><Pressable onPress={pick} style={styles.outline}><Text style={styles.outlineText}>OPEN LOCAL FILE</Text></Pressable></View><Text style={styles.panelLabel}>INPUT / {from.toUpperCase()}</Text><TextInput value={input} onChangeText={setInput} multiline autoCapitalize="none" autoCorrect={false} style={styles.editor}/><Pressable onPress={run} style={styles.transform}><Text style={styles.transformText}>TRANSFORM LOCALLY</Text></Pressable><Text style={styles.panelLabel}>OUTPUT / {to.toUpperCase()}</Text><TextInput value={output} editable={false} multiline style={[styles.editor, styles.output]} placeholder="Output appears here." placeholderTextColor="#706b65"/><Pressable onPress={share} disabled={!output} style={[styles.share, !output && styles.shareDisabled]}><Text style={styles.shareText}>SAVE OR SHARE OUTPUT</Text></Pressable><Text style={styles.foot}>For media, PDF, Office and archive routes, use the desktop or CLI engine with its local adapters.</Text></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe:{ flex:1, backgroundColor:"#121211" }, page:{ padding:20, gap:12 }, header:{ paddingTop:20, paddingBottom:18 }, kicker:{ color:"#9cf3ff", fontSize:10, letterSpacing:2, fontWeight:"700" }, title:{ color:"#f5f1e9", fontSize:42, fontWeight:"800", letterSpacing:-2, marginTop:8 }, subtitle:{ color:"#aaa39a", marginTop:4, fontSize:14 }, route:{ flexDirection:"row", alignItems:"center", justifyContent:"space-between", borderTopWidth:1, borderBottomWidth:1, borderColor:"#35332f", paddingVertical:13 }, routeText:{ color:"#bcb5ac", fontSize:10, fontWeight:"700", letterSpacing:1 }, arrow:{ color:"#d83a32" }, card:{ backgroundColor:"#1e1d1b", borderWidth:1, borderColor:"#37342f", padding:16 }, label:{ color:"#918a81", fontSize:10, fontWeight:"700", letterSpacing:1.5 }, row:{ flexDirection:"row", flexWrap:"wrap", gap:8, marginTop:10 }, chip:{ borderWidth:1, borderColor:"#4a453e", paddingVertical:8, paddingHorizontal:10 }, chipActive:{ borderColor:"#9cf3ff", backgroundColor:"#183135" }, chipText:{ color:"#aaa39a", fontSize:10, fontWeight:"700" }, chipTextActive:{ color:"#d2fbff" }, outline:{ borderWidth:1, borderColor:"#4a453e", alignItems:"center", padding:12, marginTop:18 }, outlineText:{ color:"#bdf7ff", fontSize:11, fontWeight:"700", letterSpacing:1 }, panelLabel:{ color:"#918a81", fontSize:10, fontWeight:"700", letterSpacing:1.4, marginTop:7 }, editor:{ minHeight:180, backgroundColor:"#191816", borderWidth:1, borderColor:"#35322e", color:"#efe9df", padding:13, fontFamily:"monospace", fontSize:12, lineHeight:19, textAlignVertical:"top" }, output:{ color:"#bdf7ff" }, transform:{ backgroundColor:"#d83a32", alignItems:"center", padding:15, marginVertical:4 }, transformText:{ color:"white", fontSize:11, fontWeight:"800", letterSpacing:1.3 }, share:{ borderWidth:1, borderColor:"#9cf3ff", alignItems:"center", padding:14 }, shareDisabled:{ opacity:.35 }, shareText:{ color:"#bdf7ff", fontSize:11, fontWeight:"800", letterSpacing:1.2 }, foot:{ color:"#817a71", fontSize:12, lineHeight:18, marginTop:8, marginBottom:20 } });
